#!/bin/bash

echo "════════════════════════════════════════════════════════════════════"
echo "         🧪 TESTE SIMPLES DE MULTI-LINE PASTE"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Comportamento esperado:"
echo ""
echo "1. Cole um texto multi-linha"
echo "2. O texto deve aparecer no campo de input como uma única string"
echo "3. Quando pressionar Enter, deve processar todo o texto"
echo "4. Você pode continuar digitando após o paste"
echo ""
echo "Texto para copiar (3 linhas):"
echo "────────────────────────────"
echo "Primeira linha"
echo "Segunda linha"
echo "Terceira linha"
echo "────────────────────────────"
echo ""
echo "Como deve aparecer no input:"
echo "❯ Primeira linha"
echo "Segunda linha"
echo "Terceira linha█"
echo ""
echo "Se você digitar ' teste' depois:"
echo "❯ Primeira linha"
echo "Segunda linha"
echo "Terceira linha teste█"
echo ""
echo "Iniciando interface em 3 segundos..."
sleep 3

MCP_USER=fabio node interface-v2/mcp-ink-cli.mjs