#!/bin/bash

echo "════════════════════════════════════════════════════════════════════"
echo "           ✨ TESTE DO NOVO COMPONENTE MULTILINE"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Agora com um componente customizado elegante!"
echo ""
echo "Funcionalidades:"
echo "✅ Renderização adequada de múltiplas linhas"
echo "✅ Cursor sempre no final do texto"
echo "✅ Indentação automática para linhas adicionais"
echo "✅ Placeholder quando vazio"
echo "✅ Compatível com paste e digitação normal"
echo ""
echo "────────────────────────────────────────────"
echo "TESTE 1: Cole este texto multi-linha"
echo "────────────────────────────────────────────"
echo "Primeira linha de teste"
echo "Segunda linha de teste"
echo "Terceira linha de teste"
echo ""
echo "Esperado:"
echo "❯ Primeira linha de teste"
echo "  Segunda linha de teste"
echo "  Terceira linha de teste█"
echo ""
echo "────────────────────────────────────────────"
echo "TESTE 2: Digite texto após colar"
echo "────────────────────────────────────────────"
echo "Depois de colar, digite: ' e mais texto'"
echo ""
echo "Esperado:"
echo "❯ Primeira linha de teste"
echo "  Segunda linha de teste"
echo "  Terceira linha de teste e mais texto█"
echo ""
echo "Iniciando interface em 3 segundos..."
sleep 3

MCP_USER=fabio node interface-v2/mcp-ink-cli.mjs