#!/bin/bash

echo "════════════════════════════════════════════════════════════════════"
echo "      🔍 TESTE: PRESERVAÇÃO DE CONTEXTO APÓS CANCELAMENTO"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "Este teste verifica se mensagens canceladas permanecem no contexto"
echo ""
echo "INSTRUÇÕES DETALHADAS:"
echo ""
echo "PASSO 1:"
echo "  Digite: 'Oi, sou o Fábio, teste'"
echo "  Pressione ENTER"
echo "  Quando começar a processar, pressione ESC para cancelar"
echo ""
echo "PASSO 2:"
echo "  Agora digite: 'Escreva exatamente o que eu digitei na interação anterior'"
echo "  Pressione ENTER"
echo ""
echo "✅ SUCESSO: A IA deve responder mencionando 'Oi, sou o Fábio, teste'"
echo "❌ FALHA: Se a IA disser que não houve interação anterior"
echo ""
echo "OBSERVAÇÕES:"
echo "- Com DEBUG ativo, você verá mensagens como:"
echo "  '[Debug] Added to commandHistory: \"Oi, sou o Fábio, teste\"...'"
echo "  '[Debug] Added cancellation marker to history'"
echo ""
echo "Iniciando interface com DEBUG em 3 segundos..."
echo ""
sleep 3

MCP_USER=fabio node interface-v2/mcp-ink-cli.mjs --debug