#!/bin/bash

echo "============================================"
echo "Teste Fase 1: Atualização do fullHistory"
echo "============================================"
echo ""
echo "1. Inicie a aplicação com debug:"
echo "   MCP_USER=fabio node interface-v2/mcp-ink-cli.mjs --debug"
echo ""
echo "2. Digite: 'O brasil foi criado em que ano?'"
echo "3. Pressione ESC durante o processamento"
echo "4. Observe nos logs:"
echo "   - [Debug] Adding cancelled message to fullHistory"
echo "   - [Debug] Added cancellation marker to history"
echo "   - [Debug] fullHistory now has X messages"
echo ""
echo "5. Digite: 'O que eu disse na pergunta anterior?'"
echo "6. Verifique se a IA agora reconhece a mensagem cancelada"
echo ""
echo "SUCESSO esperado:"
echo "- IA responde: 'Você perguntou \"O brasil foi criado em que ano?\"'"
echo ""